dist: bionic
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get install cmake libboost-python-dev
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - travis_retry pip install --upgrade pip setuptools wheel
  - conda install pytorch torchvision cpuonly -c pytorch
  - pip install --upgrade pytest

install:
  - python setup.py install

script:
  - pytest test/

deploy:
  - provider: pypi
    user: 1adrianb
    password:
      secure: JOAPrJhBk9TOq1RZquSroieGgNXl4ZcZOy9a1nefzLnU+hzTCsxRbm4aoYFpnqxJ1za99bzCUnYSE6vYLYIVae2SJysA7IcZ00Qr9bOu5ALmwiMIPMkMNrKRaoxwFoZOy6QgS06EPXn6O3fNuOMTfp+CjlKDACczC2rhrjxog5fqgjbKMntMthpgA6/FjpLM4nkwVNpXRp64aZ6QV8dGQsIWAkiohgoSY7Im1QdM4uy9dQONHJdQGpcOWy7Y5sBshCvQN/fO17yNW57iX9K3lmiRLkA5HkF5hN9GDrCXgtE2zBUnkeS1+b3A6jLZ75ibwgl6OF2dh7DxPmtCcH/Mn4pGuV30MNU7Yoi4+9t1VIrpseo4EsorJTdRvyKwhHvjWMY9YHdFIrctG6PTByM7Cz2qxWummYmJlT6Jm5U/jeQE5JrvnvHUr/be6TKoB1j+urnahcas2VVKh9d984//WYkcIZ2c6gFigHMfdw+mmsr4b/BDhJw6t2VsYcT2RfETYjl9LzxnY4VMWZ7zs7g/XmQznDi8G5gCrW21+ix17J5xNbAoGOXhC6BxMv9mLl/G2CEzngqUu0zy6/WVs0PA1TUiwvBki0wUvlpKttHwAon2ywCw1/zxjcqCH9mGUtf/X0xibFcxo0DV4rv6QtFq+TYg1LROJmEP5LMnnOaeRXY=
    on: 
      tags: true
      branch: master
      condition: "$TRAVIS_PYTHON_VERSION == 3.6"
    skip_cleanup: true


matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8
      script: flake8
